spring:
  application:
    name: gounanjiao-gateway
  cloud:
    gateway:
      routes:
        - id: gounanjiao-api_route
          uri: lb://gounanjiao-api
          predicates:
            - Path=/api/gounanjiaoapi/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
    nacos:
      discovery:
        namespace: 6babf0e8-5f39-4581-9c96-d3b69a2bfb75
        server-addr: 192.168.174.110:8847
      config:
        server-addr: 192.168.174.110:8847
server:
  port: 88